---
parameters:
  - name: env
    type: string
  - name: condition
    type: string
  - name: dependsOn
    type: string
stages:
  - stage: ${{ parameters.env }}
    condition: ${{ parameters.condition }}
    dependsOn: ${{ parameters.dependsOn }}
    jobs:
      - job: deploy_application
        displayName: Deployt the Application
        pool: '$(windows_pool)'
        steps:
          - template: Deploy-Apps-template.yml # step template reference

      - job: smoke_test
        displayName: Run Smoke Test
        pool: '$(windows_pool)'
        dependsOn: deploy_application
        condition: in(dependencies.deploy_application.result, 'Succeeded')
        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                write-host "Setup running the Smoke Test"

...
